In [1]:
import pandas as pd

In [9]:
pd.__version__  #VERSION CHECKING

'2.2.2'

In [17]:
df = pd.DataFrame([11,22,33], columns=["Cols_Name"])     #CREATION OF DATAFRAME
print(df)

   Cols_Name
0         11
1         22
2         33

In [18]:
print(type(df))       #DATATYPE CHECK

<class 'pandas.core.frame.DataFrame'>

In [19]:
data = {                                  
    'Name':['Prem','Rohan','Shyam'],
    'Age':[16,19,20],
    'Salary':[90000,20000,50000]
}

In [20]:
df = pd.DataFrame(data)         #ADDING AND PRINTING OF DATA
print(df)

    Name  Age  Salary
0   Prem   16   90000
1  Rohan   19   20000
2  Shyam   20   50000

In [21]:
df.head(2)            #GET FIRST 2 ROWS

    Name  Age  Salary
0   Prem   16   90000
1  Rohan   19   20000

In [22]:
df.tail(1)           #GET LAST 1 ROWS

    Name  Age  Salary
2  Shyam   20   50000

In [23]:
df.shape           #NUMBER OF ROWS AND COLUMNS

(3, 3)

In [24]:
df.columns        #COLUMNS USED

Index(['Name', 'Age', 'Salary'], dtype='object')

In [27]:
df.rename(columns={'Salary':'Monthly_Salary'},inplace=True)                #RENAME OR UPDATING COLUMN NAME
print(df)

    Name  Age  Monthly_Salary
0   Prem   16           90000
1  Rohan   19           20000
2  Shyam   20           50000

In [28]:
df.info()            #COLUMN INFO

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            3 non-null      object
 1   Age             3 non-null      int64
 2   Monthly_Salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [29]:
df.describe()        #OPERATION ON NUMERIC VALUES

             Age  Monthly_Salary
count   3.000000        3.000000
mean   18.333333    53333.333333
std     2.081666    35118.845843
min    16.000000    20000.000000
25%    17.500000    35000.000000
50%    19.000000    50000.000000
75%    19.500000    70000.000000
max    20.000000    90000.000000

In [31]:
df.to_csv('Test_data.csv',index=False)      #SAVE DATAFRAME

In [32]:
load_csv=pd.read_csv('Test_data.csv')       #LOAD DATAFRAME

In [33]:
load_csv

    Name  Age  Monthly_Salary
0   Prem   16           90000
1  Rohan   19           20000
2  Shyam   20           50000

In [34]:
df[['Name']]             #GETTING ANY SINGLE COLUMN

    Name
0   Prem
1  Rohan
2  Shyam

In [35]:
df[['Name','Monthly_Salary']]          #GETTING MULTIPLE COLUMNS

    Name  Monthly_Salary
0   Prem           90000
1  Rohan           20000
2  Shyam           50000

In [36]:
df.loc[0]            #GETTING ROW INDEX INFO

Name               Prem
Age                  16
Monthly_Salary    90000
Name: 0, dtype: object

In [39]:
df.loc[df.Name=='Prem']        #GET ENTIRE ROW

   Name  Age  Monthly_Salary
0  Prem   16           90000

In [40]:
df.loc[0:2]            #GET RANGE FOR NUMBER OF ROWS

    Name  Age  Monthly_Salary
0   Prem   16           90000
1  Rohan   19           20000
2  Shyam   20           50000

In [41]:
df.iloc[0:2]             #GET RANGE FOR NUMBER OF INDEX ROWS

    Name  Age  Monthly_Salary
0   Prem   16           90000
1  Rohan   19           20000

In [42]:
df

    Name  Age  Monthly_Salary
0   Prem   16           90000
1  Rohan   19           20000
2  Shyam   20           50000

In [47]:
df_filter=df[df['Age']>18]            #USE FILTER FOR AGE>18
df_filter

    Name  Age  Monthly_Salary
1  Rohan   19           20000
2  Shyam   20           50000

In [48]:
df[(df['Age']>18)&(df['Monthly_Salary']<60000)]        #USE FILTER FOR AGE>18 AND SALARY<60000

    Name  Age  Monthly_Salary
1  Rohan   19           20000
2  Shyam   20           50000

In [49]:
df.where(df['Age']<18)                    #USE OF WHERE TO ENTIRE TABLE CELLS VALUE

   Name   Age  Monthly_Salary
0  Prem  16.0         90000.0
1   NaN   NaN             NaN
2   NaN   NaN             NaN

In [50]:
df.where(df['Age']<18, other='Ineligible')          #USE OTHER ATTRIBUTE TO CHANGE NAME FOR CELLS NOT AVAILABLE

         Name         Age Monthly_Salary
0        Prem          16          90000
1  Ineligible  Ineligible     Ineligible
2  Ineligible  Ineligible     Ineligible

In [51]:
df

    Name  Age  Monthly_Salary
0   Prem   16           90000
1  Rohan   19           20000
2  Shyam   20           50000

In [52]:
df['Team']=['CEO','HR','Manager']            #ADD TEAM COLUMN TO THE DATAFRAME

In [53]:
df

    Name  Age  Monthly_Salary     Team
0   Prem   16           90000      CEO
1  Rohan   19           20000       HR
2  Shyam   20           50000  Manager

In [54]:
df['Bonus']=df['Monthly_Salary']*0.2            #ADD BONUS COLUMN BY USING SALARY

In [55]:
df

    Name  Age  Monthly_Salary     Team    Bonus
0   Prem   16           90000      CEO  18000.0
1  Rohan   19           20000       HR   4000.0
2  Shyam   20           50000  Manager  10000.0

In [57]:
df.loc[len(df)]=['Jishan',22,40000,'Owner',8000]           #ADD ROW TO THE DATAFRAME

In [58]:
df

     Name  Age  Monthly_Salary     Team    Bonus
0    Prem   16           90000      CEO  18000.0
1   Rohan   19           20000       HR   4000.0
2   Shyam   20           50000  Manager  10000.0
3  Jishan   22           40000    Owner   8000.0

In [59]:
df.loc[0,'Monthly_Salary']=95000                    #ADD ROW TO DATAFRAME USING INDEX

In [60]:
df

     Name  Age  Monthly_Salary     Team    Bonus
0    Prem   16           95000      CEO  18000.0
1   Rohan   19           20000       HR   4000.0
2   Shyam   20           50000  Manager  10000.0
3  Jishan   22           40000    Owner   8000.0

In [63]:
df.loc[df.Name=='Rohan','Monthly_Salary']=25000             #UPDATING THE CELL VALUE IN DATAFRAME
df

     Name  Age  Monthly_Salary     Team    Bonus
0    Prem   16           95000      CEO  18000.0
1   Rohan   19           25000       HR   4000.0
2   Shyam   20           50000  Manager  10000.0
3  Jishan   22           40000    Owner   8000.0

In [72]:
df=df.drop(df[df.Name=='Jishan'].index)               #DELETE ROW FROM DATAFRAME BY NAME PERMANENTLY
df

    Name  Age  Monthly_Salary     Team    Bonus
0   Prem   16           95000      CEO  18000.0
1  Rohan   19           25000       HR   4000.0
2  Shyam   20           50000  Manager  10000.0

In [74]:
df.drop(1,axis=0)                        #DELETE THE ROW USING INDEX AXIS=0

    Name  Age  Monthly_Salary     Team    Bonus
0   Prem   16           95000      CEO  18000.0
2  Shyam   20           50000  Manager  10000.0

In [75]:
df=df.drop('Bonus',axis=1)                #DELETE THE COLUMN USING COLUMN_NAME AND AXIS=1
df

    Name  Age  Monthly_Salary     Team
0   Prem   16           95000      CEO
1  Rohan   19           25000       HR
2  Shyam   20           50000  Manager

In [76]:
df.sort_values('Monthly_Salary')         #SORT THE VALUES IN SALARY COLUMN ASCENDING BY DEFAULT

    Name  Age  Monthly_Salary     Team
1  Rohan   19           25000       HR
2  Shyam   20           50000  Manager
0   Prem   16           95000      CEO

In [78]:
df.sort_values('Monthly_Salary', ascending=False)          #DESCENDING THE VALUES IN SALARY

    Name  Age  Monthly_Salary     Team
0   Prem   16           95000      CEO
2  Shyam   20           50000  Manager
1  Rohan   19           25000       HR

In [85]:
df['DOJ'] = ['2024-01-01', '2024-01-15', '2024-03-28']        #ADDED DOJ COLUMN IN DATAFRAME
df

    Name  Age  Monthly_Salary     Team         DOJ
0   Prem   16           95000      CEO  2024-01-01
1  Rohan   19           25000       HR  2024-01-15
2  Shyam   20           50000  Manager  2024-03-28

In [86]:
df['DOJ'].dtype                  #CHECKED DATATYPE FOR DATE WHICH IS OBJECT

dtype('O')

In [95]:
df['DOJ']=pd.to_datetime(df['DOJ'])          #CONVERTED DATATYPE TO DATE 
df

    Name  Age  Monthly_Salary     Team        DOJ
0   Prem   16           95000      CEO 2024-01-01
1  Rohan   19           25000       HR 2024-01-15
2  Shyam   20           50000  Manager 2024-03-28

In [96]:
df['DOJ'].dtype                  #DATATYPE IS NOW DATE M8[ns]

dtype('<M8[ns]')

In [97]:
df1=df                           #COPIED DATAFRAME

In [98]:
df1['DOJ1']=['01-03-2024', '03-06-2025', '14-10-2026']               #ENTER DATE IN DIFERENT FORMAT
df1

    Name  Age  Monthly_Salary     Team        DOJ        DOJ1
0   Prem   16           95000      CEO 2024-01-01  01-03-2024
1  Rohan   19           25000       HR 2024-01-15  03-06-2025
2  Shyam   20           50000  Manager 2024-03-28  14-10-2026

In [99]:
df1['DOJ1'].dtype         #AGAIN DATATYPE IS OBJECT

dtype('O')

In [101]:
df1['DOJ1']=pd.to_datetime(df1['DOJ1'], format='%d-%m-%Y')       #CHANGED DATATYPE WITH FORMAT
df1

    Name  Age  Monthly_Salary     Team        DOJ       DOJ1
0   Prem   16           95000      CEO 2024-01-01 2024-03-01
1  Rohan   19           25000       HR 2024-01-15 2025-06-03
2  Shyam   20           50000  Manager 2024-03-28 2026-10-14

In [102]:
df1['DOJ1'].dtype

dtype('<M8[ns]')

In [103]:
df=df.drop('DOJ1',axis=1)         #DELETE DOJ1

In [104]:
df

    Name  Age  Monthly_Salary     Team        DOJ
0   Prem   16           95000      CEO 2024-01-01
1  Rohan   19           25000       HR 2024-01-15
2  Shyam   20           50000  Manager 2024-03-28

In [105]:
df['DOJ'].dt.year      #ACCESS YEAR OF JOINING

0    2024
1    2024
2    2024
Name: DOJ, dtype: int32

In [106]:
df['DOJ'].dt.day       #ACCESS DATE OF JOINING

0     1
1    15
2    28
Name: DOJ, dtype: int32

In [109]:
df['DOJ'].dt.day_name()      #ACCESS DAY OF JOINING

0      Monday
1      Monday
2    Thursday
Name: DOJ, dtype: object

In [110]:
df

    Name  Age  Monthly_Salary     Team        DOJ
0   Prem   16           95000      CEO 2024-01-01
1  Rohan   19           25000       HR 2024-01-15
2  Shyam   20           50000  Manager 2024-03-28

In [112]:
df['DOJ']+ pd.Timedelta(days=50)        #AFTER CERTAIN PERIOD OF TIME CHECKING

0   2024-02-20
1   2024-03-05
2   2024-05-17
Name: DOJ, dtype: datetime64[ns]

In [113]:
df

    Name  Age  Monthly_Salary     Team        DOJ
0   Prem   16           95000      CEO 2024-01-01
1  Rohan   19           25000       HR 2024-01-15
2  Shyam   20           50000  Manager 2024-03-28

In [115]:
df.isnull()       #CHECK IF ANY VALUE IS NULL IN DATAFRAME

    Name    Age  Monthly_Salary   Team    DOJ
0  False  False           False  False  False
1  False  False           False  False  False
2  False  False           False  False  False

In [119]:
import numpy as np                                               #USED NUMPY TO DELETE VALUE IN ROW
df.loc[df.Name=='Shyam', 'Monthly_Salary']=np.nan         
df

    Name  Age  Monthly_Salary     Team        DOJ
0   Prem   16         95000.0      CEO 2024-01-01
1  Rohan   19         25000.0       HR 2024-01-15
2  Shyam   20             NaN  Manager 2024-03-28

In [120]:
df.isnull()          #NOW CHECK AGAIN ALL VALUES

    Name    Age  Monthly_Salary   Team    DOJ
0  False  False           False  False  False
1  False  False           False  False  False
2  False  False            True  False  False

In [121]:
df.isnull().sum()             #CHECK BY USING SUM FUNCTION IN WHICH COLUMN

Name              0
Age               0
Monthly_Salary    1
Team              0
DOJ               0
dtype: int64

In [127]:
df=df.fillna(45000)             #USE FILLNA TO FILL BLANK SPACE
df

    Name  Age  Monthly_Salary     Team        DOJ Month
0   Prem   16         95000.0      CEO 2024-01-01     1
1  Rohan   19         25000.0       HR 2024-01-15     3
2  Shyam   20         45000.0  Manager 2024-03-28     3

In [123]:
df['Month']=['1','3','3']         #ADDED NEW COLUMN MONTH

In [128]:
df

    Name  Age  Monthly_Salary     Team        DOJ Month
0   Prem   16         95000.0      CEO 2024-01-01     1
1  Rohan   19         25000.0       HR 2024-01-15     3
2  Shyam   20         45000.0  Manager 2024-03-28     3

In [132]:
df['Month'].value_counts()          #VALUE_COUNTS FOR MONTH

Month
3    2
1    1
Name: count, dtype: int64

In [142]:
df

    Name  Age  Monthly_Salary     Team        DOJ Month
0   Prem   16         95000.0      CEO 2024-01-01     1
1  Rohan   19         25000.0       HR 2024-01-15     3
2  Shyam   20         45000.0  Manager 2024-03-28     3

In [144]:
df[df['Month']==3].value_counts()          ##ONLY COUNTS FOR 3 MONTH

Series([], Name: count, dtype: int64)

In [146]:
df.groupby('Month')['Monthly_Salary'].sum()        #USE GROUPBY FOR SALARY SUM IN SPECIFIC MONTH

Month
1    95000.0
3    70000.0
Name: Monthly_Salary, dtype: float64

In [148]:
df.groupby('Month').agg({'Monthly_Salary': 'mean', 'Name': 'count'})        #USE GROUPBY ON AGGREGATION ON SALARY MEAN AND NAME COUNT

       Monthly_Salary  Name
Month
1             95000.0     1
3             35000.0     2

In [149]:
df1 = pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})          #1ST DATAFRAME
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [150]:
df2 = pd.DataFrame({'ID':[1,2,2,4],'Score':[88,96,77,79]})          #2ND DATAFRAME
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [151]:
pd.concat([df1,df2], axis=0)          #MERGE OR JOIN ONE-AFTER-OTHER BY ROW

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [152]:
pd.concat([df1,df2], axis=1)           #MERGE OR JOIN SIDE-BY-SIDE BY COLUMN

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

In [153]:
pd.merge(df1,df2, how='inner', on='ID')         #USE INNER JOIN

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [155]:
pd.merge(df1,df2, how='inner', left_on='ID', right_on='ID')          #USE LEFT AND RIGHT INNER JOIN

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [176]:
pd.merge(df1,df2, how='outer', on='ID')         #USE OUTER JOIN ON DATAFRAME

   ID Name  Score
0   1    A   88.0
1   2    B   96.0
2   2    B   77.0
3   3    C    NaN
4   4  NaN   79.0